### ISSUE TITLE
Point cloud import is kinda all over the place

### ISSUE THREAD

**Issue by dganzella** [atteneder/DracoUnity#70] opened 2023-09-14 20:05 UTC
Hey!

Point cloud importing is kinda not working. After running draco.ConvertDracoMeshToUnity, I needed to make a few adjustments

Both the Index format is wrong, and no submesh is being created

so here is how to solve it for now:

```
            var mesh = await draco.ConvertDracoMeshToUnity(data);

            mesh.indexFormat = mesh.vertexCount > 65535 ?
                IndexFormat.UInt32 : IndexFormat.UInt16;

            mesh.SetIndices(
                Enumerable.Range(0, mesh.vertexCount).ToArray(),
                MeshTopology.Points, 0
            );

            mesh.UploadMeshData(true);
```

**Comment by dganzella** [comment] 2023-09-22 18:21
I still have no idea what was happening to the Poor mesh inside ConvertDracoMeshToUnity

but I had an issue which was noticed by our QA analyst that it was randomly disappearing then moving the camera

here is the fixed code, I could onlu fix it my making a copy
,
```

            var data = File.ReadAllBytes(filepath);

            var draco = new DracoMeshLoader();

            var mesh = await draco.ConvertDracoMeshToUnity(data);

            var mesh_not_broken = new Mesh();

            mesh_not_broken.SetVertices(mesh.vertices);
            mesh_not_broken.SetColors(mesh.colors);

            mesh_not_broken.indexFormat = mesh.vertexCount > 65535 ?
                IndexFormat.UInt32 : IndexFormat.UInt16;

            mesh_not_broken.SetIndices(
                Enumerable.Range(0, mesh.vertexCount).ToArray(),
                MeshTopology.Points, 0
            );

            mesh_not_broken.UploadMeshData(true);

            setupPointCloud(mesh_not_broken);
```

**Comment by atteneder** [comment] 2023-11-07 15:28
Hi @dganzella,

Thanks for reporting. I could not reproduce that behavior with stock test files and custom created ones. Can you give me a sample .drc file that reproduces this error.

Also, which version of Unity and DracoUnity are you using?

Thanks

**Comment by atteneder** [comment] 2023-11-08 10:44
Might be related to #64

**Comment by atteneder** [comment] 2023-11-08 10:47
Or maybe even #63 . The lack of correct bounds might confuse the culling, so point clouds are (not) rendered when they shouldn't. Can you try replacing your fix with a [`Mesh.RecalculateBounds.`](https://docs.unity3d.com/ScriptReference/Mesh.RecalculateBounds.html)?

**Comment by atteneder** [comment] 2024-01-30 21:49
Both #63 and #64 have been fixed in [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/), the successor of this repository/package.

**Closed as completed by atteneder** 2024-01-30 21:49 UTC
Labels: bug, question
