### ISSUE TITLE
DracoUnity compress a mesh in Unity to ship out to backend?

### ISSUE THREAD

**Issue by tex447** [atteneder/DracoUnity#6] opened 2021-02-03 14:35 UTC
We would like to use DracoUnity for our current Unity Project. Our plan is to upload GLTF files to our Unity WebGL app via the browser, have that app compress them with Draco to be shipped off to our backend. Is DracoUnity capable of this?

Thanks!
Dave

**Comment by atteneder** [comment] 2021-02-03 14:54
Thanks for reaching out.

Unfortunately DracoUnity currently only supporte decompression.  Compression is not available in the Editor and not at runtime (if I read correctly, you'd need the latter).

I'd try the following:

- Consider compressing meshes server-side
  - You WebGL app will be smaller and load faster
  - Might be faster overall (depending on device and connection speed)
- Does Google's Unity integration support what you need? (I haven't checked theirs in a while, they might have improved it)

Unrelated, but I'm curious: Do you use glTFast for loading glTF or something else?

Kind regards,
Andreas

**Comment by atteneder** [comment] 2021-02-03 14:55
this is a duplicate of #1

**Closed by atteneder** 2021-02-03 14:55 UTC
Labels: enhancement
