### ISSUE TITLE
Unity crashes during encoding

### ISSUE THREAD

**Issue by bruno1308** [atteneder/DracoUnity#49] opened 2022-07-15 14:05 UTC
Hi!
I have a model with UV coordinates and vertex colors that crashes the whole editor when trying to encode it. The last line to be executed before crashing is:
`dracoEncoderEncode(dracoEncoder, false);` inside `public static unsafe EncodeResult[] EncodeMesh` on DracoEncoder.cs
Unity 2021.3.6 with 4.0.2 version of the package

Crash:
![image](https://user-images.githubusercontent.com/8274038/179238723-ff5b7c50-2004-497b-ac15-62b4dfadfcde.png)

The mesh info:
![image](https://user-images.githubusercontent.com/8274038/179239418-25468bfd-dc3a-4db2-b250-180109b191be.png)

**Comment by atteneder** [comment] 2022-08-26 10:13
Hi @bruno1308  and thanks for reporting.

I'd love to look at it. Can you please provde this asset (or any other test asset) that triggers the crash?

**Comment by atteneder** [comment] 2023-11-07 11:04
Closing due to missing reproduction assets/meshes.

**Closed by atteneder** 2023-11-07 11:04 UTC
Labels: bug
