### ISSUE TITLE
Failed to load 'dracoenc_unity.dll' because one or more of its dependencies could not be loaded

### ISSUE THREAD

**Issue by hcshen** [atteneder/DracoUnity#65] opened 2023-06-19 08:36 UTC
This error is always reported on the win11 computer, but I do not know what library is relied on here

**Comment by John-Storm** [comment] 2023-08-01 10:31
I had the same issue with Windows 11. The issue was resolved by installing Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by amakhno** [comment] 2023-08-15 09:33
It looks like the encoding plugins, `.dll` at least, haven't been updated along with the unity scripts

You can use [the most recent binaries](https://github.com/atteneder/draco/releases/tag/unity2.0.0) that have lacking functions and different signatures

**Comment by Sov3rain** [comment] 2023-10-17 08:06
Hey, I have the same issue on Windows 10 latest, clean install. Built the app using Mono and IL2CPP, still missing a .dll. I need to distribute my app as a standalone, not asking users to install redistributable packages for VS, did you guys found a way to include the missing DLL in the build?

**Comment by atteneder** [comment] 2023-10-26 13:41
The next DracoUnity version will have one DLL file only, so the encoding dll problem should be gone.

**Comment by atteneder** [comment] 2023-10-26 13:44
If someone can confirm (or falsify) that installing Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022 solves the problem, I'd put that in the docs.
Thanks

**Comment by Sov3rain** [comment] 2023-10-26 13:45
I can confirm that installing the redistributable package linked above by @John-Storm fixes the issue.

**Comment by atteneder** [comment] 2024-01-30 21:51
Please transition to [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/), the successor of this repository/package.

The original pitfall is now documented here:

<https://docs.unity3d.com/Packages/com.unity.cloud.draco@5.0/manual/troubleshooting.html#native-library-on-windows>

Thanks for bringing it to our attention!

**Closed as completed by atteneder** 2024-01-30 21:51 UTC
Labels: bug, documentation
