### ISSUE TITLE
Draco decode fails with `EntryPointNotFoundException: DecodeDracoMeshStep1`

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/DracoUnity#40] opened 2022-02-21 23:15 UTC
Seems when trying to import a file that uses Draco mesh compression in 2020.3.25f1, the import fails with an error message regarding the entry point not being found:
![image](https://user-images.githubusercontent.com/2693840/155036608-8dd1f42f-9e14-4a7e-8497-e3ca975b4dd9.png)

**Versions**
- Unity 2020.3.25f1
- glTFast 4.5.0 (OpenUPM)
- Draco 3D Data Compression 3.3.2 (OpenUPM)
- Windows 11, also reprodues on Windows 10

**File**
[25023528_Servogetriebemotor_0_52kW_jt.zip](https://github.com/atteneder/DracoUnity/files/8112527/25023528_Servogetriebemotor_0_52kW_jt.zip)

**Comment by atteneder** [comment] 2022-02-22 08:05
Hi @hybridherbst ,

are you on Windows?

**Comment by hybridherbst** [comment] 2022-02-22 08:55
Hi, yep, tested on both Windows 10 and Windows 11.

Windows 10 for some reason has a better error message:
![image](https://user-images.githubusercontent.com/2693840/155097137-0de02c49-1d79-4def-af8f-e6001e51ed00.png)

**Comment by atteneder** [comment] 2022-05-09 14:08
@hybridherbst sorry, briefly forgot about it.

I cannot reproduce. Which Burst version are you running? There's been known issues about native functions with some 1.4 versions.

**Comment by atteneder** [comment] 2022-05-09 14:34
What I tried:

- Copied the 2CylinderEngine Draco variant into `Assets` (which worked)
- Closed Unity
- Wiped `Library` folder
- Opened project again, resulting in successful re-import

Can you reproduce it reliably in some way?

**Comment by atteneder** [comment] 2023-11-08 10:52
I believe it's the same problem as #65 . Maybe you could try out if the proposed solution helps. Thanks!

**Comment by atteneder** [comment] 2024-01-31 08:54
Closing this one, as I think the proposed solution is a valid fix. Re-open if it still occurs.

**Closed by atteneder** 2024-01-31 08:54 UTC
Labels: bug
